[build-system]
requires = []
build-backend = "flit_core.buildapi"

[project]
name = "photocad-docs"
authors = [{ name = "alanzhang", email = "alanzhang@latitudeda.com" }]
dynamic = ["version", "description"]
